# Generated by Django 3.0.5 on 2020-04-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200429_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qt_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score_sum',
            field=models.IntegerField(default=0),
        ),
    ]
