STORES = [
    ('AMER', 'AMERICANAS'),
    ('SUBM', 'SUBMARINO'),
    ('MAGA', 'MAGALU'),
    ('CASA', 'CASAS BAHIA'),
    ('KABO', 'KABOOM'),
    ('PICH', 'PICHAU'),
]

RELOAD_PRODUCTS_AUTO = False

MIN_TIME_TO_CLIENT_AVALIATE = 0
MAX_TIME_TO_CLIENT_AVALIATE = 24

MAX_TIME_TO_ATTENDANT_AVALIATE = 30

MIN_VOTES_AMOUNT_TO_PREMIUM = 15
MIN_SCORE_TO_PREMIUM = 4

POINTS = {
    'LIKE': 5, #ok
    'REMOVE_LIKE': -5, #ok
    'REVIEW': 50, #ok
    'CLIENT': 100, #ok
    'ATTENDANT': 200, #ok
}

MAX_PAGE_SIZE = 10