# Generated by Django 3.0.5 on 2020-04-29 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('AMER', 'AMERICANAS'), ('SUBM', 'SUBMARINO'), ('MAGA', 'MAGALU'), ('CASA', 'CASAS BAHIA'), ('KABO', 'KABOOM'), ('PICH', 'PICHAU')], max_length=20)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
            ],
        ),
    ]
