# Generated by Django 3.0.5 on 2020-05-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20200501_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='likes',
            new_name='like_users',
        ),
    ]
