# Generated by Django 3.0.5 on 2020-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20200501_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.FloatField(default=0),
        ),
    ]
