# Generated by Django 3.0.5 on 2020-05-04 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20200503_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
