# Generated by Django 3.0.5 on 2020-05-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200501_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='verified_state',
            field=models.CharField(choices=[('UN', 'Ainda não respondido'), ('NO', 'Não atendido'), ('YES', 'Atendido')], default='UN', max_length=3),
        ),
    ]
