# Generated by Django 3.0.5 on 2020-05-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendance_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='verified_state',
            field=models.CharField(choices=[('NO', 'Não atendido'), ('YES', 'Atendido')], default=None, max_length=3, null=True),
        ),
    ]
