# Generated by Django 3.0.5 on 2020-05-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200501_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='client_score',
            field=models.IntegerField(default=0),
        ),
    ]
