# Generated by Django 3.0.5 on 2020-05-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance_client_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='client_score',
            field=models.IntegerField(default=3),
        ),
    ]
