# Generated by Django 3.0.5 on 2020-05-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20200502_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='client_score',
            new_name='attendant_score',
        ),
    ]
