# Generated by Django 3.0.5 on 2020-05-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20200502_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendant_score',
            new_name='client_score',
        ),
    ]
