# Generated by Django 3.0.5 on 2020-05-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20200502_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='client_score',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
