# Generated by Django 3.0.5 on 2020-05-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_auto_20200502_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendant_vote',
            new_name='attendant_was_evaluated',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='client_vote',
            new_name='client_was_evaluated',
        ),
    ]
