# Generated by Django 3.0.5 on 2020-05-04 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20200503_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendant_score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='client_score',
            field=models.FloatField(default=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
