# Generated by Django 3.0.5 on 2020-04-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200429_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CEL', 'CELULAR'), ('MOV', 'MÓVEL')], max_length=20),
        ),
    ]
