# Generated by Django 3.0.5 on 2020-04-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qt_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='score_sum',
            field=models.IntegerField(default=0),
        ),
    ]
