# Generated by Django 3.0.5 on 2020-04-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_product'),
        ('products', '0006_auto_20200430_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
