# Generated by Django 3.0.5 on 2020-04-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('product_type', models.CharField(default=None, max_length=50, null=True)),
                ('qt_votes', models.IntegerField(default=0)),
                ('score_sum', models.IntegerField(default=0)),
            ],
        ),
    ]
