# Generated by Django 3.0.5 on 2020-04-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qt_votes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='score_sum',
        ),
    ]
