# Generated by Django 3.0.5 on 2020-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200430_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_image',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
