# Generated by Django 3.0.5 on 2020-05-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200502_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_image',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
